<?php

namespace Tcp;

use EasySwoole\Core\Socket\Response;
use EasySwoole\Core\Socket\TcpController;
use EasySwoole\Core\Swoole\ServerManager;
use EasySwoole\Core\Swoole\Task\TaskManager;

class Test extends TcpController
{
    function actionNotFound(?string $actionName)
    {
//        parent::actionNotFound($actionName); // TODO: Change the autogenerated stub
        $this->response()->write("{$actionName} not found");
    }

    function test(){
        $this->response()->write(time());
    }

    function args(){
        var_dump($this->request()->getArgs());
    }

    function delay(){
        $client = $this->client();
        TaskManager::async(function() use($client){
           sleep(1);
           Response::response($client,'this is delay message at '.time());
        });
    }

    function close(){
        $this->response()->write("you are goging to close");
        $client = $this->client();
        TaskManager::async(function() use ($client){
            sleep(2);
            ServerManager::getInstance()->getServer()->close($client->getFd());
        });
    }

    function who(){
        $this->response()->write("you fd is ".$this->client()->getFd());
    }
}

